### ISSUE TITLE
Feature Request: Optimize card spacing / temperature and humidity location

### ISSUE THREAD

**Issue by FragMenthor** [argaar/comfortable-environment-card#16]
Made a mokup of an more compact / visual representation of your card;
Maybe the temperature and humidity (or all) ICON COLORS could change to reflect actual conditions:

![image](https://github.com/argaar/comfortable-environment-card/assets/74264069/5b110764-f34d-4f84-8580-1edfc266f9a9)

Or even:

![image](https://github.com/argaar/comfortable-environment-card/assets/74264069/73d379cc-056f-474b-9595-1bd0cab0b3dc)

Thanks for your card!

**Comment by argaar** [comment]
@FragMenthor 
I think it's pretty similar to your mockup

All Indexes
![all](https://github.com/argaar/comfortable-environment-card/assets/8555329/4a847555-8a74-4b7e-8a24-0b526098c0c9)

Only Heat Index
![hi](https://github.com/argaar/comfortable-environment-card/assets/8555329/fb5fb674-5d3f-4dc4-a9e3-a04bebe0e9f3)

Only Discomfort Index
![di](https://github.com/argaar/comfortable-environment-card/assets/8555329/ef5004e0-bd5e-4c63-9d90-770cb55e89a1)

If you think it's ok, I'll commit the new release

**Comment by FragMenthor** [comment]
Wow!!! NICE!!! Thanks 🙏!!!!

**Comment by FragMenthor** [comment]
Thank you very much for the time you are spending with this; But the last update broke something for me:

![image](https://github.com/argaar/comfortable-environment-card/assets/74264069/3a5a3b81-b253-4799-98cb-4f81bdb5b709)

I already refreshed the browser cache and even tested on an new anonymous window and browser...
Any thoughts?

**Comment by argaar** [comment]
Probably something in conflict and the card/js is unable to be loaded the right way, so you can't find in the dashboard.

Could you attach a screenshot (or copy the text) from the developer console? Open it, move to Console tab and refresh the dashboard, you should see a lot of red lines about my card (the name and offending line of code should be at the right of the screen)

**Comment by FragMenthor** [comment]
Well, I don't have logs for you, but I redownloaded the module and it now works :) Thanks!
