### ISSUE TITLE
HI computation is wrong

### ISSUE THREAD

**Issue by GaPhi** [argaar/comfortable-environment-card#2]
Test with 1.1°C and 94%RH gives HI=59.05°C

I think it would be better to follow the study formulas as they gives a much better result around -1.1°C...

**Comment by drac0linux** [comment]
I see the same problem.

This card says my garage, with a temp of 56.52°F and a relative humidity of 44.85% has a heat index of 88.2°F.

An online calculator on the national weather service website shows the heat index should be 54°F.
![Screenshot_20231217_234717_Home Assistant](https://github.com/argaar/comfortable-environment-card/assets/3718039/be892d34-a1e1-4b38-8e41-51e08349f472)
![Screenshot_20231217_235043_Chrome](https://github.com/argaar/comfortable-environment-card/assets/3718039/03c69cc6-c050-4f0a-8dfb-e67e4de14328)
