### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by Andurilll** [argaar/comfortable-environment-card#20]
I would like to Translate to German. How and where?

**Comment by argaar** [comment]
you just need to add a new lang file in src/localize/languages called de.json (you can copy/paste the en.json and rename it)
then translate all the occurences in the file to German.
also you need to edit the file src/localize/localize.ts adding the new import in the first line

when everything is ok please submit a pull request so I can merge the new lang

and of course, thanks for your effort

**Comment by Andurilll** [comment]
Done

do you know if there is a swiss-german translation possible and if yes, what would be the short name ( example en, de, uk,...)
