### ISSUE TITLE
Card no longer works after 2024.1.6 HA update

### ISSUE THREAD

**Issue by papperone** [argaar/comfortable-environment-card#26]
Since I updated my HA to 2024.1.6 card doesn't work and shows only temp/hum (see picture)
![immagine](https://github.com/argaar/comfortable-environment-card/assets/28104633/56394dd8-9132-4ea3-ba6f-225244d400a0)
Configuration hasn't changed of course:
![immagine](https://github.com/argaar/comfortable-environment-card/assets/28104633/6b31d2b5-c119-47a0-8f35-b90d7820f35c)

**Comment by argaar** [comment]
Could you please open the developer tools in your browser (F12 on Chrome/Firefox), switch to "Console" tab, and reload the page to look if the card throws out an error?

You should see something like this (Firefox):

![image](https://github.com/argaar/comfortable-environment-card/assets/8555329/9fdb1ba1-45f8-464d-9446-55a10bc005c2)

I've the same HA version and checked that the card is working as usual, either with the Default Theme or the others installed

**Comment by papperone** [comment]
> Could you please open the developer tools in your browser (F12 on Chrome/Firefox), switch to "Console" tab, and reload the page to look if the card throws out an error?
> 
> You should see something like this (Firefox):
> 
> ![image](https://private-user-images.githubusercontent.com/8555329/301483131-9fdb1ba1-45f8-464d-9446-55a10bc005c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MTY5MzEsIm5iZiI6MTcwNjgxNjYzMSwicGF0aCI6Ii84NTU1MzI5LzMwMTQ4MzEzMS05ZmRiMWJhMS00NWY4LTQ2NGQtOTQ0Ni01NWExMGJjMDA1YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTk0MzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAwOWRjOWI5NmEyNTJjOTJlNzMyMmUyYjAzODhlMGVmMWU2ZDgwN2I0MjlkZDU1Mzk4ODk1YzQzNmRkNjY5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wY2z59vx7i0JHdEM8eFat3Y-eP9OozTAiJtw78SgEMY)
> 
> I've the same HA version and checked that the card is working as usual, either with the Default Theme or the others installed

I see same as you
![immagine](https://github.com/argaar/comfortable-environment-card/assets/28104633/01d8b653-e9ef-444b-82af-ad86f26bc848)

**Comment by papperone** [comment]
ok I've a good news, it works back but I had to add the line "**show_index: ALL**" which should not be mandatory, and it was not there before.
Now I tried to add it manuallay and the card works as it should...

**Comment by argaar** [comment]
fixed in readme
