### ISSUE TITLE
Specify the exact number of decimals to show for vlaues

### ISSUE THREAD

**Issue by AlexKusnezov** [argaar/comfortable-environment-card#30]
Hey, I have a sensor group which shows the temperature for my house, but it give me a lso of decimal dumber despite sepcifying it in the group settings:
<img width="564" alt="Screen Shot 2024-03-04 at 14 26 15" src="https://github.com/argaar/comfortable-environment-card/assets/33514406/1d89e271-a3e8-4bfb-b6ef-78c37e22e7ad">
<img width="374" alt="Screen Shot 2024-03-04 at 14 26 46" src="https://github.com/argaar/comfortable-environment-card/assets/33514406/00f7345a-e192-4b9c-a836-e1ecdf902c2c">
It would be awesome if the card would either respect this setting or just sepcify decimlals by hand like it is in:
https://github.com/kalkih/mini-graph-card

btw thanks for the awesome card, it rules!

**Comment by argaar** [comment]
You're right I should handle decimals, will code it asap, and thanks for pointing it out
