### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by argaar** [argaar/comfortable-environment-card#31]
Since release 1.5.10 introduces new parameters, an update to all translations files to localize the new description
under _configurator.display_precision_ is needed

New element:

"display_precision": "Display N numbers after decimal"

**Comment by argaar** [comment]
latest release (1.6.0) also includes a new option "configurator.show_realvalues"

since the new changes, the languages that needs translations are:

- [ ] Czech
- [ ] Dutch
- [ ] German
- [x] English
- [ ] French
- [ ] Greek
- [ ] Hungarian
- [x] Italian
- [ ] Portuguese
- [ ] Russian  ( only configurator.show_realvalues is needed )
- [ ] Slovak  ( only configurator.show_realvalues is needed )
- [ ] Spanish
- [ ] Ukrainian

**Comment by artt652** [comment]
* [x]  Russian  ( only configurator.show_realvalues is needed ) #40

**Comment by argaar** [comment]
Translations moved to Locize (as in Readme).
For all future translations, please use the platform instead of submitting a new PR
