### ISSUE TITLE
Smaller Bars?

### ISSUE THREAD

**Issue by GnFlala** [argaar/comfortable-environment-card#32]
Hi,

Is there any way to make the bars smaller?

**Comment by argaar** [comment]
not at the moment, at least not from the card itself, maybe if you have some plugin able to edit the css you could achieve the result, otherwise I have to make it user defined in the next release.

When you write "smaller" you mean you want to change the width or the height of the bars?

**Comment by GnFlala** [comment]
Thanks for the reply man.

I mean the width but your answer is also the solution. Custom css and it can be done.

Thanks in advance
