### ISSUE TITLE
Improve text color inside the graph

### ISSUE THREAD

**Issue by igorsantos07** [argaar/comfortable-environment-card#42]
This definitely isn't readable :see_no_evil: 

![image](https://github.com/argaar/comfortable-environment-card/assets/532299/42973f1b-3335-435c-9b6a-6b69b6569b9a)

It could use black or white as text color depending on the index value?

**Comment by igorsantos07** [comment]
Doing some quick tweaks in DevTools, I would suggest the following:
- change border and text to be always black, because against the:
  - start of the bar: definitely readable and [WCAG agrees](https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=0570B0) (more if you consider most of the text isn't against the very start of the bar)
  - middle of the bar: black against white :man_shrugging: 
  - the red in the end of the bar: readable to me, but according to WCAG it would be better to change that red a bit, to [`B80000`](https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=B80000) instead of `B60000` (so it hits AA for large text)
- bonus: make that text bold

As a frontend developer for the past decade or so, I would also suggest removal of box-shadows and text-shadows :eyes: I hope you don't feel offended, as this might seem like a matter of personal taste :pray: 
But shadows are not present in the usual Home Assistant theme, and in all honesty it kinda makes it feel like a dated UI element (think "Web 2.0" buttons). Sometimes, simplicity is better than overdoing, and there are other means to make text readable against different backgrounds.

Bonus: make the index values follow the decimal places option.

Mocks below:
![image](https://github.com/argaar/comfortable-environment-card/assets/532299/d1ca202d-f2e8-4a5e-b404-904c64546f6c)
![image](https://github.com/argaar/comfortable-environment-card/assets/532299/73dc59dd-c41c-4bd0-9f7a-52ba5caa3160)
![image](https://github.com/argaar/comfortable-environment-card/assets/532299/6f22ea02-a0cf-4802-aff5-f9ae0a024ee6)

I can submit a PR with those changes, if you agree to my ideas :)

**Comment by argaar** [comment]
Don't worry I'm not offended at all, I love to share different points of view and receive suggestions

Of course I'll accept a PR, otherwise I can code it by myself but every bit of help is good 👍

**Comment by artt652** [comment]
I'd want suggest ho hide descriptions in case unavailable of entities, 
 currently in this case card shows wrong description. 
![Screenshot_20240511_213908_Home Assistant](https://github.com/argaar/comfortable-environment-card/assets/62139160/a91d95f4-641a-426b-ba33-f983cc352f39)
