### ISSUE TITLE
Suggestion: make this an integration as well

### ISSUE THREAD

**Issue by igorsantos07** [argaar/comfortable-environment-card#44]
An integration, instead of a card, would make those values even more useful and more customizable, allowing users to display raw values, levels and descriptions in all sorts of cards :)

Not sure how you would go about sharing code, though - I guess you could extract the calculations to an integration, and make the card just a frontend to whatever values are calculated by the integration?

**Comment by argaar** [comment]
I never looked at how integrations works, but this also comes up to my mind sometimes, I'll try to get some experience about it in order to split the frontend part from the "backend" one

**Comment by igorsantos07** [comment]
I would consider this sort of a dup, given the [Thermal Comfort integration provides various indexes](https://github.com/dolezsa/thermal_comfort/blob/2.2/documentation/sensors.md) as actual values that can be tracked with graphs and whatnot. And then, you can create your own UI with a gauge, for instance, if needed.

An alternate idea would be to join forces with that developer (or fork it, given it looks abandoned) and build UIs for those calculations, instead of having two separate integrations doing "mostly" the same thing :)
